### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by dlecan** [SchweizerischeBundesbahnen/api-devportal#1]
What is the license of this project ? Is it "MIT", as declared in [package.json](https://github.com/SchweizerischeBundesbahnen/api-devportal/blob/develop/package.json#L4) ?

I advise you to read https://help.github.com/articles/licensing-a-repository/ in order to make it explicite.

Thank you.

**Comment by kyubisation** [comment]
Added license

Thank you for bringing it up
